const products = [
        //phones
        {
                "productName":"OnePlus Nord CE 3 Lite 5G (Pastel Lime, 256 GB)  (8 GB RAM)",
                "price":21989,
                "description":"One plus CE3 lite.. What a brilliant concept.. I loved it.. Super display quality.. Best battery backup.. Fast charging with 80w... Superb performance.. Very smoothly working pubg game.. And camera is ok from this price.. Totally i love this one plus phone... Thanks🤩",
                "category":"phone",
                "productImage":"https://rukminim2.flixcart.com/image/128/128/xif0q/mobile/a/o/z/nord-ce-3-lite-5g-ce2099-oneplus-original-imagzj3wqxzgquah.jpeg?q=70",
                "brand":"oneplus",
                "rating":4.4,
        },
        {
                "productName":"OnePlus Nord CE 2 Lite 5G (Blue Tide, 128 GB)  (6 GB RAM)",
                "price":17177,
                "description":"I am using this Phone from last 2 months battery fall down bit fast but it also charged very fast overall good 👍.",
                "category":"phone",
                "productImage":"https://rukminim2.flixcart.com/image/128/128/xif0q/mobile/k/w/k/-original-imagg2abzhxjckxu.jpeg?q=70",
                "brand":"oneplus",
                "rating":4.4,
        },
        {
                "productName":"APPLE iPhone 13 (Midnight, 128 GB)",
                "price":52499,
                "description":"iPhone 13. boasts an advanced dual-camera system that allows you to click mesmerising pictures with immaculate clarity. Furthermore, the lightning-fast A15 Bionic chip allows for seamless multitasking, elevating your performance to a new dimension. A big leap in battery life, a durable design, and a bright Super Retina XDR display facilitate boosting your user experience.",
                "category":"phone",
                "productImage":"https://rukminim2.flixcart.com/image/128/128/ktketu80/mobile/s/l/c/iphone-13-mlpf3hn-a-apple-original-imag6vzz5qvejz8z.jpeg?q=70",
                "brand":"iphone",
                "rating":4.7,
        },
        {
                "productName":"APPLE iPhone 13 (Starlight, 128 GB)",
                "price":52499,
                "description":"iPhone 13. boasts an advanced dual-camera system that allows you to click mesmerising pictures with immaculate clarity. Furthermore, the lightning-fast A15 Bionic chip allows for seamless multitasking, elevating your performance to a new dimension. A big leap in battery life, a durable design, and a bright Super Retina XDR display facilitate boosting your user experience.",
                "category":"phone",
                "productImage":"https://rukminim2.flixcart.com/image/128/128/ktketu80/mobile/6/n/d/iphone-13-mlpg3hn-a-apple-original-imag6vpyghayhhrh.jpeg?q=70",
                "brand":"iphone",
                "rating":4.7,
        },
        {
                "productName":"APPLE iPhone 11 (Black, 64 GB)",
                "price":36999,
                "description":"The iPhone 11 boasts a gorgeous all-screen Liquid Retina LCD that is water resistant up to 2 metres for up to 30 minutes. Moreover, the ultra-wide 13 mm lens has a 120-degree field of view for four times more scenes, and the 26 mm wide lens provides up to 100% Autofocus in low light.",
                "category":"phone",
                "productImage":"https://rukminim2.flixcart.com/image/128/128/k2jbyq80pkrrdj/mobile-refurbished/x/j/s/iphone-11-128-d-mwm02hn-a-apple-0-original-imafkg242ugz8hwc.jpeg?q=70",
                "brand":"iphone",
                "rating":4.6,
        },
        {
                "productName":"APPLE iPhone 11 (Black, 64 GB)",
                "price":36999,
                "description":"The iPhone 11 boasts a gorgeous all-screen Liquid Retina LCD that is water resistant up to 2 metres for up to 30 minutes. Moreover, the ultra-wide 13 mm lens has a 120-degree field of view for four times more scenes, and the 26 mm wide lens provides up to 100% Autofocus in low light.",
                "category":"phone",
                "productImage":"https://rukminim2.flixcart.com/image/128/128/k2jbyq80pkrrdj/mobile-refurbished/x/j/s/iphone-11-128-d-mwm02hn-a-apple-0-original-imafkg242ugz8hwc.jpeg?q=70",
                "brand":"iphone",
                "rating":4.6,
        },
        {
                "productName":"APPLE iPhone 12 (Blue, 64 GB)",
                "price":48999,
                "description":"Dive into a world of crystal-clear visuals with this iPhone’s Super Retina XDR Display. This beast of a smartphone packs the A14 Bionic chip to make for blazing-fast performance speeds. On top of that, its Dual-camera System, along with Night Mode, helps you click amazing pictures and selfies even when the lighting isn’t as good as you’d want it to be.",
                "category":"phone",
                "productImage":"https://rukminim2.flixcart.com/image/128/128/kg8avm80/mobile/y/7/n/apple-iphone-12-dummyapplefsn-original-imafwg8dpyjvgg3j.jpeg?q=70",
                "brand":"iphone",
                "rating":4.6,
        },
        //laptop
        {
                "productName":"Lenovo LOQ Intel Core i7 13th Gen 13620H - (16 GB/512 GB SSD/Windows 11 Home/6 GB Graphics/NVIDIA GeForce RTX 4050) 15IRH8 Gaming Laptop  (15.6 Inch, Storm Grey, 2.4 kg, With MS Office)",
                "price":99990,
                "description":"The Lenovo LOQ Gaming Laptop is not just a device; it's a masterpiece crafted to elevate your gaming experience to unprecedented heights. Unleash the power within, seize the victory, and reign supreme in the gaming realm. Get your hands on the Lenovo LOQ Gaming Laptop today and embark on an unforgettable journey of gaming excellence.",
                "category":"laptop",
                "productImage":"https://rukminim2.flixcart.com/image/128/128/xif0q/computer/a/b/a/15irh8-laptop-lenovo-original-imagrzs9mwzbjcxn.jpeg?q=70",
                "brand":"lanovo",
                "rating":4.3,
        },
        {
                "productName":"APPLE 2022 MacBook AIR M2 - (8 GB/512 GB SSD/Mac OS Monterey) MLY23HN/A  (13.6 Inch, Starlight, 1.24 kg)",
                "price":137990,
                "description":"Charged in a blazing-fast speed with the next-level M2 chip, this redesigned Apple’s notebook comes with mind blowing and has an excellent battery backup that can last up to 18 hours, which comes with an aluminium enclosure. ",
                "category":"laptop",
                "productImage":"https://rukminim2.flixcart.com/image/128/128/xif0q/computer/x/h/o/-original-imagfdfppdgspafh.jpeg?q=70",
                "brand":"macbook",
                "rating":4.9,
        },
        {
                "productName":"APPLE 2021 Macbook Pro M1 Max - (32 GB/1 TB SSD/Mac OS Monterey) MK1H3HN/A  (16.2 inch, Silver, 2,2 kg)",
                "price":303990,
                "description":"iMovie, Siri, GarageBand, Pages, Numbers, Photos, Keynote, Safari, Mail, FaceTime, Messages, Maps, Stocks, Home, Voice Memos, Notes, Calendar, Contacts, Reminders, Photo Booth, Preview, Books, App Store, Time Machine, TV, Music, Podcasts, Find My, QuickTime Player",
                "category":"laptop",
                "productImage":"https://rukminim2.flixcart.com/image/128/128/kuyf8nk0/computer/g/z/q/mk1e3hn-a-laptop-apple-original-imag7yzmv57cvg3f.jpeg?q=70",
                "brand":"macbook",
                "rating":4.4,
        },
        {
                "productName":"APPLE 2020 Macbook Air M1 - (8 GB/512 GB SSD/Mac OS Big Sur) MGNE3HN/A  (13.3 inch, Gold, 1.29 kg)",
                "price":109990,
                "description":"               Built-in Apps: iMovie, Siri, GarageBand, Pages, Numbers, Photos, Keynote, Safari, Mail, FaceTime, Messages, Maps, Stocks, Home, Voice Memos, Notes, Calendar, Contacts, Reminders, Photo Booth, Preview, Books, App Store, Time Machine, TV, Music, Podcasts, Find My, QuickTime Player",
                "category":"laptop",
                "productImage":"https://rukminim2.flixcart.com/image/128/128/khdqnbk0/computer/s/2/g/apple-original-imafxfyqykyghjg6.jpeg?q=70",
                "brand":"macbook",
                "rating":4.6,
        },
        {
                "productName":"APPLE 2020 Macbook Air M1 - (8 GB/256 GB SSD/Mac OS Big Sur) MGN93HN/A  (13.3 inch, Silver, 1.29 kg)",
                "price":79990,
                "description":"This Apple’s notebook is super slim and lightweight and can get charged quickly with the Apple M1 chip. Handle your projects at ease with the super fast 8-core CPU. Elevate your high-end games and graphics-intensive apps to the next level with its GPU of up to 8-core. Powered with a 16-core Neural Engine, accelerate your machine learning tasks with this laptop. This laptop is impressive with its fanless design and operates silently. Has a powerful battery capacity that can last up to 18 hours. Empower your day with this MacBook Air that is portable and is easy to carry around. ",
                "category":"laptop",
                "productImage":"https://rukminim2.flixcart.com/image/128/128/khdqnbk0/computer/f/y/t/apple-original-imafxfyqydgvrkzv.jpeg?q=70",
                "brand":"macbook",
                "rating":4.7,
        },
        {
                "productName":"Acer One Core i3 11th Gen 1115G4 - (8 GB/512 GB SSD/Windows 11 Home) AO 14 Z 8-415 Thin and Light Laptop  (14 Inch, Silver, 1.49 Kg)",
                "price":25990,
                "description":"You can experience the power of the Intel Core processor and Intel Iris Graphics card to reign over the game world. The 8 GB of RAM with an upgradable RAM of 32 GB are featured in this laptop so that you have enough space to store for all your applications. The sleek and minimalist design of this laptop makes it classy and portable so that you can easily carry it with you wherever you want. The whooping 512 GB of M.2PCIe SSD ensures maximum storage capacity to this Acer laptop. With a wide range of ports you can easily connect multiple devices at the same time to enhance your productivity.",
                "category":"laptop",
                "productImage":"https://rukminim2.flixcart.com/image/128/128/xif0q/computer/6/5/g/-original-imagtke7erkzwzfp.jpeg?q=70",
                "brand":"acer",
                "rating":4.1,
        },
        {
                "productName":"DELL Inspiron Core i3 11th Gen 1115G4 - (8 GB/512 GB SSD/Windows 11 Home) Inspiron 3511 Thin and Light Laptop  (38 cm, Carbon Black, 1.8 kg, With MS Office)",
                "price":36490,
                "description":"Heating problem.Battery backup is not upto the mark.Audio jack stopped working after some time.Hanging issue.Software updation not work properly.",
                "category":"laptop",
                "productImage":"https://rukminim2.flixcart.com/image/128/128/xif0q/computer/u/m/k/-original-imagzyfzhzcw8wvp.jpeg?q=70",
                "brand":"dell",
                "rating":4.1,
        },
        {
                "productName":"HP Laptop Core i3 11th Gen 1115G4 - (8 GB/512 GB SSD/Windows 11 Home) 15s-fq2717TU Thin and Light Laptop  (15.6 Inch, Natural Silver, 1.69 Kg, With MS Office)",
                "price":38990,
                "description":"Amazing the product was superb thanku Flipcart smooth touch and best features long lasting battery backup ❣️ valuable for money u now buy this hp laptop",
                "category":"laptop",
                "productImage":"https://rukminim2.flixcart.com/image/128/128/xif0q/computer/c/l/u/-original-imagp7pgcy8e6eta.jpeg?q=70",
                "brand":"hp",
                "rating":4.2,
        },
        {
                "productName":"realme Book (Slim) Core i3 11th Gen 1115G4 - (8 GB/256 GB SSD/Windows 10 Home) RMNB1001 Thin and Light Laptop  (14 inch, Real Blue, 1.38 kg)",
                "price":32990,
                "description":"MS Office is not included with this realme laptop. It can be purchased separately.The Windows 11 upgrade rollout plan is scheduled to begin in late 2021 and will continue into 2022. The specific timing will vary as per the device.",
                "category":"laptop",
                "productImage":"https://rukminim2.flixcart.com/image/128/128/ksez24w0/computer/h/8/9/rmnb1001-thin-and-light-laptop-realme-original-imag5zhgcstmjbxg.jpeg?q=70",
                "brand":"realme",
                "rating":4.4,
        },
        {
                "productName":"Infinix X2 Slim Intel Core i3 11th Gen 1115G4 - (8 GB/512 GB SSD/Windows 11 Home) XL23 Thin and Light Laptop  (14 inch, Green, 1.24 kg)",
                "price":23990,
                "description":"The Infinix INBook X2 Slim laptop is the perfect choice for you if you are a globetrotter. This slim and sleek laptop is about 14.8 mm slim and weighs around 1.24 kg so that you can easily carry it with you wherever you go. Its 65 W USB Type-C charger helps to charge your laptop up to 60% in about 55 minutes so that you do not have to wait around for long. The multi-utility charger also allows you to charge your smartphone so that you do not have to carry two chargers while travelling. This laptop has a long-lasting battery life of up to 9 to 10 hours so that you can get all your work done without having to recharge it every now and then. Featuring an Intel Core processor chip, this laptop comes with a wide storage capacity and high RAM for smooth and efficient operations. ",
                "category":"laptop",
                "productImage":"https://rukminim2.flixcart.com/image/128/128/xif0q/computer/k/k/e/inbook-thin-and-light-laptop-infinix-original-imagpyjduraxwu4m.jpeg?q=70",
                "brand":"Infinix",
                "rating":4.1,
        },
        //fashion
        {
                "productName":"Woven Banarasi Cotton Silk Saree  (Yellow)",
                "price":699,
                "description":"Refresh your Wardrobe with Saree from VBHP FASHION. A Traditional looking soft saree with Rich look Pallu. Our Saree is made up of genuine Fabric, simple yet trendy which make your look Attractive. Step out Royally and create Paradise wherever you go with our saree. It can be worn on occasions like festivals, Weeding, Social events, Functions, Parties and even casual outings. Our Saree gives you all, What you find Fashion and Stylish zone. Look Classy and Elegant in this piece and revel in the comfort of its Fabric. You will be the centre of Attraction once you wear it.",
                "category":"fashion",
                "productImage":"https://rukminim2.flixcart.com/image/128/128/kzrbiq80/sari/j/4/d/free-mk-zal-cosbila-fashion-unstitched-original-imagbpgmfvx7cehu.jpeg?q=70",
                "brand":"COSBILA",
                "rating":4.1,
        },
        {
                "productName":"Printed, Blocked Printed Hand Batik Chiffon Saree  (Pink, White)",
                "price":399,
                "description":"Beautifully designed Indian Traditional ethnic regular wear sarees made of high-quality fabric Chiffon which have batik block printed design. • MIRCHI FASHION brings you a nice addition to the wardrobe of every fashionable female, who wants to look glamorous and distinct. This sari comes with matching Chiffon printed blouse fabric, which can be stitched according to your comfort Up to 32 to 42 Inches. This saree is ideal for festivals, occasional, parties and social/friends/family get-together, ceremonies or rituals, business functions wherever you want to flaunt your style. Also saree design and color combination are suitable for girls or women of across all age or region. Wear it with matching accessories to get complemented on next ethnic wear look. • MIRCHI FASHION Sarees brings together the Ethnic Fashion from the Indian subcontinent to Indian wear lovers across the world, with a variety of popular and trendy ethnic products for various occasions - festive wear, parties wear, regular ethnic wear to contemporary Indian suits-salwar kameez and beachwear. You Can Consider This Saree If You Are Looking For Saree New 2023 Simple Chiffon Print Saree Fancy Saree 2023 Latest Saree Collection 2023 Soft Saree Saree New2023 Design Mirchi Fashion Saree Chiffon Simple Saree Daily Use Saree",
                "category":"fashion",
                "productImage":"https://rukminim2.flixcart.com/image/128/128/xif0q/sari/p/k/s/free-37995-mirchi-fashion-unstitched-original-imagn24huyy7w7sx.jpeg?q=70",
                "brand":"MIRCHI",
                "rating":4.2,
        },
        {
                "productName":"Woven Banarasi Cotton Silk Saree  (Blue, Pink)",
                "price":699,
                "description":"When one thinks of the Kurti set,one thinks comfort.The high comfort factor is what makes the Kurti Pant & Dupatta a form of clothing loved by all.The Kurti set is a versatile piece of clothing that can be made in order to adapt to any season or occasion.During the harsh Indian summers,Cotton and Rayon kurtis set are in everyones to get and wear list due to its effortless style and comfort level.In a similar way,Woolen kurtas set are also worn during winters.",
                "category":"fashion",
                "productImage":"https://rukminim2.flixcart.com/image/128/128/xif0q/sari/n/t/e/free-mk-zal-cosbila-fashion-unstitched-original-imagkuzjj9gwh6j6.jpeg?q=70",
                "brand":"COSBILA",
                "rating":4.2,
        },
        {
                "productName":"Men Straight Full Sleeve Multicolor Shrug",
                "price":274,
                "description":"Designed to cement the vibe of your outfit just like a perfectly chosen coat, you can throw this shrug over pretty much anything to get an instantly elevated look. It can also complete your outfit and showcase your personality. Jackets are a favourite amongst men of all occupations thanks to its stylish and casual appearance - a rugged look that works perfectly on the weekend",
                "category":"fashion",
                "productImage":"https://rukminim2.flixcart.com/image/128/128/kfsl18w0/jacket/e/m/p/l-ind00037-s-indra-fashion-original-imafw6dzyc9fhaxk.jpeg?q=70",
                "brand":"INDRA",
                "rating":4.4,
        },
        {
                "productName":"Men Printed Round Neck Pure Cotton Dark Green T-Shirt",
                "price":284,
                "description":"Look your stylish best in this trendy new design of men's dark green printed full sleeve round neck t-shirt from the latest collection of Urbano Fashion. The youthful & fashionable all-over printed design, high-quality & soft 100% cotton fabric, custom fit make it a must have for your wardrobe. Pair this in-vogue all-over printed full sleeves t-shirt with any light shade of Urbano Fashion jeans or shorts for a fabulous casual look, and never go out of style! So go ahead, stand apart from the crowd and create your own trends. And follow no one else but yourself.",
                "category":"fashion",
                "productImage":"https://rukminim2.flixcart.com/image/128/128/xif0q/t-shirt/2/v/v/xl-aopleaffull-drgreen-urbano-fashion-original-imafvzqqbfbfvprv-bb.jpeg?q=70",
                "brand":"urbano",
                "rating":4.1,
        },
        //grocery
        {
                "productName":"Tata Tea Chakra Gold Dust Tea with Long Lasting Taste Tea Pouch  (1 kg)",
                "price":518,
                "description":"Flipkart endeavors to ensure the accuracy of the information about the products. It is pertinent to note that, actual product packaging and materials may contain more and/or different information which may include nutritional information/allergen declaration/special instruction for intended use/warning/directions etc. We recommend the consumers to always read the label carefully before using or consuming any products. Please do not solely rely on the information provided on this website. For additional information, please contact the manufacturer.",
                "category":"grocery",
                "productImage":"https://rukminim2.flixcart.com/image/128/128/l41n2q80/tea/m/a/w/1-chakra-gold-premium-1-pouch-regular-tea-tata-powder-original-imagff4ytwwvbxcf.jpeg?q=70",
                "brand":"tata tea",
                "rating":4.3,
        },
        {
                "productName":"Fortune Sunlite Refined Sunflower Oil Can  (5 L)",
                "price":699,
                "description":"Flipkart endeavors to ensure the accuracy of the information about the products. It is pertinent to note that, actual product packaging and materials may contain more and/or different information which may include nutritional information/allergen declaration/special instruction for intended use/warning/directions etc. We recommend the consumers to always read the label carefully before using or consuming any products. Please do not solely rely on the information provided on this website. For additional information, please contact the manufacturer.",
                "category":"grocery",
                "productImage":"https://rukminim2.flixcart.com/image/128/128/kflftzk0hlty2aw-0/edible-oil/2/m/z/sunlite-refined-can-sunflower-oil-fortune-original-imafw37vp5mntzzh.jpeg?q=70",
                "brand":"fortune",
                "rating":4.5,
        },
        {
                "productName":"Fortune Besan  (1 kg)",
                "price":158,
                "description":"Flipkart endeavors to ensure the accuracy of the information about the products. It is pertinent to note that, actual product packaging and materials may contain more and/or different information which may include nutritional information/allergen declaration/special instruction for intended use/warning/directions etc. We recommend the consumers to always read the label carefully before using or consuming any products. Please do not solely rely on the information provided on this website. For additional information, please contact the manufacturer.",
                "category":"grocery",
                "productImage":"https://rukminim2.flixcart.com/image/128/128/kqidx8w0/flour/r/4/5/besan-besan-fortune-original-imag4gb4hzv2qzvy.jpeg?q=70",
                "brand":"fortune",
                "rating":4.3,
        },
        {
                "productName":"LIVYOR Premium Roasted and Salted Cashew Nuts Dry Fruits  (200 g)",
                "price":173,
                "description":"Roasted to perfection, the LIVYOR Roasted and Salted Cashew Nuts provide a naturally enhanced flavour and crunch. Moreover, the addition of salt balances the taste, making them irresistible.",
                "category":"grocery",
                "productImage":"https://rukminim2.flixcart.com/image/128/128/xif0q/snack-savourie/y/u/a/200-premium-roasted-and-salted-cashew-nuts-super-nutritious-dry-original-imagjjquhegs49sh.jpeg?q=70",
                "brand":"livyor",
                "rating":4.2,
        },
        {
                "productName":"BOYO Roasted and Salted Almonds 400g (2*200g)  (2 x 200 g)",
                "price":369,
                "description":"HEALTHY SNACKING: Our almonds are roasted without a single drop of oil. They are a great healthy snack for hunger pangs, party snacking, kids snacking. A super healthy, nutritious snack to munch on at any time of the day. Vegan-friendly, keto-friendly, gluten free DELICIOUS TASTE: We use the finest ingredients and a unique roasting process which makes our almonds so delicious and amazingly scrumptious. A go to snack when you crave a healthy snack that taste great RICH IN PROTEIN: Almonds are a great source of protein with 20g in 100g of almonds. They are nutrient dense with vitamin e, manganese, magnesium, antioxidants. Helps in building immunity HIGH IN DIETARY FIBRE: Helps to maintain a healthy digestive system by promoting regular bowel movements HOW TO EAT: Traditionally eaten in the morning after being soaked overnight. Almonds are a great vegan source of making almond butter, almond milk, without compromising on any nutrition. A healthy keto friendly and vegan friendly snack! They are a great addition to smoothies, salads, oatmeal, yogurt SEARCH ENGINE: Search BOYO to see all our products PACKAGE CONTENT: 200 Gm of Roasted Almonds Himalayan Pink Salted; Quantity: 200g; Shelf Life: 180 Days; Ingredient Type: Roasted Almond",
                "category":"grocery",
                "productImage":"https://rukminim2.flixcart.com/image/128/128/kzsqykw0/snack-savourie/j/t/b/400-roasted-and-salted-almonds-400g-2-200g-box-2-boyo-original-imagbqazehmbrb46.jpeg?q=70",
                "brand":"boyo",
                "rating":3.9,
        }
]

module.exports = products
const name = {
        "productName":"",
        "price":12312,
        "description":"",
        "category":"grocery",
        "productImage":"",
        "brand":"",
        "rating":1.2,
}